// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graph.proto

package graph

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DirectedWeightedMultiGraph struct {
	Vertex               []*Vertex `protobuf:"bytes,1,rep,name=vertex,proto3" json:"vertex,omitempty"`
	Arc                  []*Arc    `protobuf:"bytes,2,rep,name=arc,proto3" json:"arc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DirectedWeightedMultiGraph) Reset()         { *m = DirectedWeightedMultiGraph{} }
func (m *DirectedWeightedMultiGraph) String() string { return proto.CompactTextString(m) }
func (*DirectedWeightedMultiGraph) ProtoMessage()    {}
func (*DirectedWeightedMultiGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{0}
}

func (m *DirectedWeightedMultiGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectedWeightedMultiGraph.Unmarshal(m, b)
}
func (m *DirectedWeightedMultiGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectedWeightedMultiGraph.Marshal(b, m, deterministic)
}
func (m *DirectedWeightedMultiGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectedWeightedMultiGraph.Merge(m, src)
}
func (m *DirectedWeightedMultiGraph) XXX_Size() int {
	return xxx_messageInfo_DirectedWeightedMultiGraph.Size(m)
}
func (m *DirectedWeightedMultiGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectedWeightedMultiGraph.DiscardUnknown(m)
}

var xxx_messageInfo_DirectedWeightedMultiGraph proto.InternalMessageInfo

func (m *DirectedWeightedMultiGraph) GetVertex() []*Vertex {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *DirectedWeightedMultiGraph) GetArc() []*Arc {
	if m != nil {
		return m.Arc
	}
	return nil
}

type Vertex struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Weight               float64  `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vertex) Reset()         { *m = Vertex{} }
func (m *Vertex) String() string { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()    {}
func (*Vertex) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{1}
}

func (m *Vertex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vertex.Unmarshal(m, b)
}
func (m *Vertex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vertex.Marshal(b, m, deterministic)
}
func (m *Vertex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vertex.Merge(m, src)
}
func (m *Vertex) XXX_Size() int {
	return xxx_messageInfo_Vertex.Size(m)
}
func (m *Vertex) XXX_DiscardUnknown() {
	xxx_messageInfo_Vertex.DiscardUnknown(m)
}

var xxx_messageInfo_Vertex proto.InternalMessageInfo

func (m *Vertex) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vertex) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Arc struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 *Vertex  `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Vertex  `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Weight               float64  `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Arc) Reset()         { *m = Arc{} }
func (m *Arc) String() string { return proto.CompactTextString(m) }
func (*Arc) ProtoMessage()    {}
func (*Arc) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{2}
}

func (m *Arc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arc.Unmarshal(m, b)
}
func (m *Arc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arc.Marshal(b, m, deterministic)
}
func (m *Arc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arc.Merge(m, src)
}
func (m *Arc) XXX_Size() int {
	return xxx_messageInfo_Arc.Size(m)
}
func (m *Arc) XXX_DiscardUnknown() {
	xxx_messageInfo_Arc.DiscardUnknown(m)
}

var xxx_messageInfo_Arc proto.InternalMessageInfo

func (m *Arc) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Arc) GetFrom() *Vertex {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Arc) GetTo() *Vertex {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Arc) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*DirectedWeightedMultiGraph)(nil), "DirectedWeightedMultiGraph")
	proto.RegisterType((*Vertex)(nil), "Vertex")
	proto.RegisterType((*Arc)(nil), "Arc")
}

func init() { proto.RegisterFile("graph.proto", fileDescriptor_3e4c656902fc0e6b) }

var fileDescriptor_3e4c656902fc0e6b = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xbf, 0xca, 0xc2, 0x30,
	0x14, 0x47, 0x49, 0x52, 0xf2, 0xc1, 0x2d, 0x7c, 0x43, 0x86, 0x1a, 0x74, 0xb0, 0x74, 0xea, 0x54,
	0x44, 0x9f, 0xa0, 0x20, 0x38, 0xb9, 0x04, 0xd4, 0xb9, 0x26, 0xb1, 0x0d, 0x28, 0x29, 0x97, 0xf8,
	0xe7, 0xf1, 0xa5, 0xb1, 0x43, 0xc5, 0xf1, 0x9e, 0xdf, 0x81, 0xc3, 0x85, 0xb4, 0xc5, 0xa6, 0xef,
	0xaa, 0x1e, 0x7d, 0xf0, 0xc5, 0x01, 0xe6, 0x5b, 0x87, 0x56, 0x07, 0x6b, 0x4e, 0xd6, 0xb5, 0x5d,
	0xb0, 0x66, 0x7f, 0xbf, 0x06, 0xb7, 0x1b, 0x1c, 0xb1, 0x04, 0xfe, 0xb0, 0x18, 0xec, 0x4b, 0x92,
	0x9c, 0x95, 0xe9, 0xfa, 0xaf, 0x3a, 0xc6, 0x53, 0x8d, 0x58, 0x64, 0xc0, 0x1a, 0xd4, 0x92, 0xc6,
	0x35, 0xa9, 0x6a, 0xd4, 0x6a, 0x00, 0xc5, 0x0a, 0xf8, 0xc7, 0x14, 0xff, 0x40, 0x9d, 0x91, 0x24,
	0x27, 0x25, 0x53, 0xd4, 0x19, 0x91, 0x01, 0x7f, 0xc6, 0x90, 0xa4, 0x39, 0x29, 0x89, 0x1a, 0xaf,
	0x42, 0x03, 0xab, 0x51, 0xff, 0xe8, 0x0b, 0x48, 0x2e, 0xe8, 0x6f, 0x51, 0x9e, 0xf4, 0x23, 0x14,
	0x33, 0xa0, 0xc1, 0x4b, 0xf6, 0x3d, 0xd1, 0xe0, 0x27, 0x91, 0x64, 0x1a, 0x39, 0xf3, 0xf8, 0xf4,
	0xe6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xf3, 0x6f, 0xaf, 0x03, 0x01, 0x00, 0x00,
}
