// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graph.proto

package graph

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaveRequest struct {
	Digraph              *DirectedWeightedMultiGraph `protobuf:"bytes,1,opt,name=digraph,proto3" json:"digraph,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{0}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetDigraph() *DirectedWeightedMultiGraph {
	if m != nil {
		return m.Digraph
	}
	return nil
}

type SaveResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{1}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type DirectedWeightedMultiGraph struct {
	Vertex               []*Vertex `protobuf:"bytes,1,rep,name=vertex,proto3" json:"vertex,omitempty"`
	Arc                  []*Arc    `protobuf:"bytes,2,rep,name=arc,proto3" json:"arc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DirectedWeightedMultiGraph) Reset()         { *m = DirectedWeightedMultiGraph{} }
func (m *DirectedWeightedMultiGraph) String() string { return proto.CompactTextString(m) }
func (*DirectedWeightedMultiGraph) ProtoMessage()    {}
func (*DirectedWeightedMultiGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{2}
}

func (m *DirectedWeightedMultiGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectedWeightedMultiGraph.Unmarshal(m, b)
}
func (m *DirectedWeightedMultiGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectedWeightedMultiGraph.Marshal(b, m, deterministic)
}
func (m *DirectedWeightedMultiGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectedWeightedMultiGraph.Merge(m, src)
}
func (m *DirectedWeightedMultiGraph) XXX_Size() int {
	return xxx_messageInfo_DirectedWeightedMultiGraph.Size(m)
}
func (m *DirectedWeightedMultiGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectedWeightedMultiGraph.DiscardUnknown(m)
}

var xxx_messageInfo_DirectedWeightedMultiGraph proto.InternalMessageInfo

func (m *DirectedWeightedMultiGraph) GetVertex() []*Vertex {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *DirectedWeightedMultiGraph) GetArc() []*Arc {
	if m != nil {
		return m.Arc
	}
	return nil
}

type Vertex struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Weight               float64  `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vertex) Reset()         { *m = Vertex{} }
func (m *Vertex) String() string { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()    {}
func (*Vertex) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{3}
}

func (m *Vertex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vertex.Unmarshal(m, b)
}
func (m *Vertex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vertex.Marshal(b, m, deterministic)
}
func (m *Vertex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vertex.Merge(m, src)
}
func (m *Vertex) XXX_Size() int {
	return xxx_messageInfo_Vertex.Size(m)
}
func (m *Vertex) XXX_DiscardUnknown() {
	xxx_messageInfo_Vertex.DiscardUnknown(m)
}

var xxx_messageInfo_Vertex proto.InternalMessageInfo

func (m *Vertex) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vertex) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Arc struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 *Vertex  `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Vertex  `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Weight               float64  `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Arc) Reset()         { *m = Arc{} }
func (m *Arc) String() string { return proto.CompactTextString(m) }
func (*Arc) ProtoMessage()    {}
func (*Arc) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e4c656902fc0e6b, []int{4}
}

func (m *Arc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arc.Unmarshal(m, b)
}
func (m *Arc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arc.Marshal(b, m, deterministic)
}
func (m *Arc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arc.Merge(m, src)
}
func (m *Arc) XXX_Size() int {
	return xxx_messageInfo_Arc.Size(m)
}
func (m *Arc) XXX_DiscardUnknown() {
	xxx_messageInfo_Arc.DiscardUnknown(m)
}

var xxx_messageInfo_Arc proto.InternalMessageInfo

func (m *Arc) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Arc) GetFrom() *Vertex {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Arc) GetTo() *Vertex {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Arc) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*SaveRequest)(nil), "graph.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "graph.SaveResponse")
	proto.RegisterType((*DirectedWeightedMultiGraph)(nil), "graph.DirectedWeightedMultiGraph")
	proto.RegisterType((*Vertex)(nil), "graph.Vertex")
	proto.RegisterType((*Arc)(nil), "graph.Arc")
}

func init() { proto.RegisterFile("graph.proto", fileDescriptor_3e4c656902fc0e6b) }

var fileDescriptor_3e4c656902fc0e6b = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0xbf, 0x6c, 0xfa, 0x45, 0x9d, 0xa8, 0x87, 0x11, 0x24, 0x94, 0x0a, 0xcd, 0x82, 0x90,
	0x83, 0x14, 0x8d, 0x47, 0x4f, 0x05, 0x41, 0x10, 0xbc, 0x6c, 0xa0, 0x9e, 0xe3, 0x66, 0x6c, 0x17,
	0xd4, 0x8d, 0xbb, 0x9b, 0xe8, 0x9f, 0x2f, 0xd9, 0x44, 0x8c, 0xd4, 0x1e, 0xe7, 0xbd, 0xdf, 0xbc,
	0x19, 0x66, 0x20, 0x5e, 0x9b, 0xb2, 0xde, 0x2c, 0x6a, 0xa3, 0x9d, 0xc6, 0xff, 0xbe, 0xe0, 0xf7,
	0x10, 0x17, 0x65, 0x4b, 0x82, 0xde, 0x1b, 0xb2, 0x0e, 0x6f, 0x60, 0xaf, 0x52, 0xde, 0x49, 0x82,
	0x79, 0x90, 0xc5, 0x79, 0xba, 0xe8, 0x9b, 0x6e, 0x95, 0x21, 0xe9, 0xa8, 0x7a, 0x24, 0xb5, 0xde,
	0x38, 0xaa, 0x1e, 0x9a, 0x17, 0xa7, 0xee, 0x3a, 0x4b, 0x7c, 0x77, 0xf0, 0x0b, 0x38, 0xec, 0xb3,
	0x6c, 0xad, 0xdf, 0x2c, 0xe1, 0x0c, 0x0e, 0x94, 0x2d, 0x1a, 0x29, 0xc9, 0x5a, 0x1f, 0xb7, 0x2f,
	0x7e, 0x04, 0x5e, 0xc2, 0x74, 0x77, 0x28, 0x9e, 0x43, 0xd4, 0x92, 0x71, 0xf4, 0x99, 0x04, 0xf3,
	0x30, 0x8b, 0xf3, 0xa3, 0x61, 0x8f, 0x95, 0x17, 0xc5, 0x60, 0xe2, 0x0c, 0xc2, 0xd2, 0xc8, 0x84,
	0x79, 0x06, 0x06, 0x66, 0x69, 0xa4, 0xe8, 0x64, 0x7e, 0x09, 0x51, 0xcf, 0xe3, 0x31, 0x30, 0x55,
	0xf9, 0x1d, 0x42, 0xc1, 0x54, 0x85, 0xa7, 0x10, 0x7d, 0xf8, 0xa1, 0x09, 0x9b, 0x07, 0x59, 0x20,
	0x86, 0x8a, 0x6b, 0x08, 0x97, 0x46, 0x6e, 0xe1, 0x29, 0x4c, 0x9e, 0x8d, 0x7e, 0xf5, 0xf0, 0xd6,
	0x2e, 0xde, 0xc2, 0x33, 0x60, 0x4e, 0x27, 0xe1, 0x5f, 0x00, 0x73, 0x7a, 0x34, 0x70, 0x32, 0x1e,
	0x98, 0xaf, 0x20, 0xdd, 0x7d, 0x85, 0x82, 0x4c, 0xab, 0x24, 0xe1, 0x15, 0x4c, 0xba, 0xc3, 0x22,
	0x0e, 0xb9, 0xa3, 0x8f, 0x4d, 0x4f, 0x7e, 0x69, 0xfd, 0xe5, 0xf9, 0xbf, 0xa7, 0xc8, 0x7f, 0xf9,
	0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x53, 0x0c, 0x32, 0xd5, 0xf4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirectedWeightedMultiGraphServiceClient is the client API for DirectedWeightedMultiGraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirectedWeightedMultiGraphServiceClient interface {
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
}

type directedWeightedMultiGraphServiceClient struct {
	cc *grpc.ClientConn
}

func NewDirectedWeightedMultiGraphServiceClient(cc *grpc.ClientConn) DirectedWeightedMultiGraphServiceClient {
	return &directedWeightedMultiGraphServiceClient{cc}
}

func (c *directedWeightedMultiGraphServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/graph.DirectedWeightedMultiGraphService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectedWeightedMultiGraphServiceServer is the server API for DirectedWeightedMultiGraphService service.
type DirectedWeightedMultiGraphServiceServer interface {
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
}

func RegisterDirectedWeightedMultiGraphServiceServer(s *grpc.Server, srv DirectedWeightedMultiGraphServiceServer) {
	s.RegisterService(&_DirectedWeightedMultiGraphService_serviceDesc, srv)
}

func _DirectedWeightedMultiGraphService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectedWeightedMultiGraphServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/graph.DirectedWeightedMultiGraphService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectedWeightedMultiGraphServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DirectedWeightedMultiGraphService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "graph.DirectedWeightedMultiGraphService",
	HandlerType: (*DirectedWeightedMultiGraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _DirectedWeightedMultiGraphService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graph.proto",
}
